2019-11-24 14:32:43,793 - remote_connection.py - __init__ - INFO -Could not connect to port 4723 on host 127.0.0.1
2019-11-24 14:32:43,793 - remote_connection.py - __init__ - INFO -Could not get IP address for host: 127.0.0.1
2019-11-24 14:32:43,794 - remote_connection.py - _request - DEBUG -POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{"platformName": "Android", "appium:deviceName": "127.0.0.1:62001", "appium:paltformVersion": "5.1.1", "appium:appPackage": "com.netease.newsreader.activity", "appium:appActivity": "com.netease.nr.biz.ad.newAd.AdActivity", "appium:automationName": "Uiautomator2"}]}, "desiredCapabilities": {"platformName": "Android", "deviceName": "127.0.0.1:62001", "paltformVersion": "5.1.1", "appPackage": "com.netease.newsreader.activity", "appActivity": "com.netease.nr.biz.ad.newAd.AdActivity", "automationName": "Uiautomator2"}}
2019-11-24 14:32:43,795 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (1): 127.0.0.1:4723
2019-11-24 14:32:44,803 - retry.py - increment - DEBUG -Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2019-11-24 14:32:44,803 - connectionpool.py - urlopen - WARNING -Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0753D170>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2019-11-24 14:32:44,803 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (2): 127.0.0.1:4723
2019-11-24 14:32:45,805 - retry.py - increment - DEBUG -Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2019-11-24 14:32:45,805 - connectionpool.py - urlopen - WARNING -Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0753D230>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2019-11-24 14:32:45,806 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (3): 127.0.0.1:4723
2019-11-24 14:32:46,806 - retry.py - increment - DEBUG -Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2019-11-24 14:32:46,806 - connectionpool.py - urlopen - WARNING -Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0753D370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2019-11-24 14:32:46,806 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (4): 127.0.0.1:4723
2019-11-24 14:32:48,824 - remote_connection.py - __init__ - INFO -Could not connect to port 4723 on host 127.0.0.1
2019-11-24 14:32:48,824 - remote_connection.py - __init__ - INFO -Could not get IP address for host: 127.0.0.1
2019-11-24 14:32:48,824 - remote_connection.py - _request - DEBUG -POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{"platformName": "Android", "appium:deviceName": "127.0.0.1:62001", "appium:paltformVersion": "5.1.1", "appium:appPackage": "com.netease.newsreader.activity", "appium:appActivity": "com.netease.nr.biz.ad.newAd.AdActivity", "appium:automationName": "Uiautomator2"}]}, "desiredCapabilities": {"platformName": "Android", "deviceName": "127.0.0.1:62001", "paltformVersion": "5.1.1", "appPackage": "com.netease.newsreader.activity", "appActivity": "com.netease.nr.biz.ad.newAd.AdActivity", "automationName": "Uiautomator2"}}
2019-11-24 14:32:48,825 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (1): 127.0.0.1:4723
2019-11-24 14:32:49,827 - retry.py - increment - DEBUG -Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2019-11-24 14:32:49,827 - connectionpool.py - urlopen - WARNING -Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x07533B30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2019-11-24 14:32:49,828 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (2): 127.0.0.1:4723
2019-11-24 14:32:50,830 - retry.py - increment - DEBUG -Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2019-11-24 14:32:50,830 - connectionpool.py - urlopen - WARNING -Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0753D8B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2019-11-24 14:32:50,830 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (3): 127.0.0.1:4723
2019-11-24 14:32:51,833 - retry.py - increment - DEBUG -Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2019-11-24 14:32:51,833 - connectionpool.py - urlopen - WARNING -Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0753D9D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2019-11-24 14:32:51,834 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (4): 127.0.0.1:4723
