2019-11-27 19:26:40,724 - remote_connection.py - __init__ - INFO -Could not connect to port 4723 on host 127.0.0.1
2019-11-27 19:26:40,725 - remote_connection.py - __init__ - INFO -Could not get IP address for host: 127.0.0.1
2019-11-27 19:26:40,725 - remote_connection.py - _request - DEBUG -POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{"platformName": "Android", "appium:deviceName": "127.0.0.1:62001", "appium:paltformVersion": "5.1.1", "appium:appPackage": "com.netease.newsreader.activity", "appium:appActivity": "com.netease.nr.biz.ad.newAd.AdActivity", "appium:automationName": "Uiautomator2"}]}, "desiredCapabilities": {"platformName": "Android", "deviceName": "127.0.0.1:62001", "paltformVersion": "5.1.1", "appPackage": "com.netease.newsreader.activity", "appActivity": "com.netease.nr.biz.ad.newAd.AdActivity", "automationName": "Uiautomator2"}}
2019-11-27 19:26:40,728 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (1): 127.0.0.1:4723
2019-11-27 19:26:41,730 - retry.py - increment - DEBUG -Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2019-11-27 19:26:41,731 - connectionpool.py - urlopen - WARNING -Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05E06970>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2019-11-27 19:26:41,731 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (2): 127.0.0.1:4723
2019-11-27 19:26:42,733 - retry.py - increment - DEBUG -Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2019-11-27 19:26:42,733 - connectionpool.py - urlopen - WARNING -Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05E06AF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2019-11-27 19:26:42,733 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (3): 127.0.0.1:4723
2019-11-27 19:26:43,735 - retry.py - increment - DEBUG -Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2019-11-27 19:26:43,735 - connectionpool.py - urlopen - WARNING -Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05E06BB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2019-11-27 19:26:43,736 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (4): 127.0.0.1:4723
