2019-11-20 16:23:34,096 - remote_connection.py - __init__ - INFO -Could not connect to port 4723 on host 0.0.0.0
2019-11-20 16:23:34,096 - remote_connection.py - __init__ - INFO -Could not get IP address for host: 0.0.0.0
2019-11-20 16:23:34,096 - remote_connection.py - _request - DEBUG -POST http://0.0.0.0:4723/wd/hub/session {"capabilities": {"firstMatch": [{"platformName": "Android", "appium:deviceName": "127.0.0.1:62001", "appium:paltformVersion": "5.1.1", "appium:appPackage": "com.netease.newsreader.activity", "appium:appActivity": "com.netease.nr.biz.ad.AdActivity", "appium:automationName": "Uiautomator2"}]}, "desiredCapabilities": {"platformName": "Android", "deviceName": "127.0.0.1:62001", "paltformVersion": "5.1.1", "appPackage": "com.netease.newsreader.activity", "appActivity": "com.netease.nr.biz.ad.AdActivity", "automationName": "Uiautomator2"}}
2019-11-20 16:23:34,097 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (1): 0.0.0.0:4723
2019-11-20 16:23:34,097 - retry.py - increment - DEBUG -Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2019-11-20 16:23:34,097 - connectionpool.py - urlopen - WARNING -Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05999950>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。')': /wd/hub/session
2019-11-20 16:23:34,098 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (2): 0.0.0.0:4723
2019-11-20 16:23:34,098 - retry.py - increment - DEBUG -Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2019-11-20 16:23:34,098 - connectionpool.py - urlopen - WARNING -Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05999AF0>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。')': /wd/hub/session
2019-11-20 16:23:34,098 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (3): 0.0.0.0:4723
2019-11-20 16:23:34,099 - retry.py - increment - DEBUG -Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2019-11-20 16:23:34,099 - connectionpool.py - urlopen - WARNING -Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05999BD0>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。')': /wd/hub/session
2019-11-20 16:23:34,099 - connectionpool.py - _new_conn - DEBUG -Starting new HTTP connection (4): 0.0.0.0:4723
